#!/usr/bin/env bash
# ==============================================================================
# DCMS system-test fixture corpus generator
#
# Builds every `fx/*` branch described in SYSTEM-TEST.MD 1.5 / 8.7 / 8.8 from
# scratch, so the deterministic half of the repo corpus is version-controlled,
# reproducible, and diffable between runs. Public repos change under us; these
# do not.
#
#   usage:  ./build-branches.sh <remote-url> [--push]
#
# Idempotent: re-running rebuilds every branch from the same base and
# force-pushes, so a branch can never drift from what this script says it is.
#
# Deliberately NOT built here (see the notes at the bottom of this file):
#   fx/lfs         -- needs git-lfs, which is intentionally absent on the
#                     DCMS host so R-WX-02 measures the real clone behaviour
#   fx/big-binary  -- GitHub rejects blobs over 100 MB without LFS
# ==============================================================================
set -euo pipefail

REMOTE="${1:?usage: build-branches.sh <remote-url> [--push]}"
PUSH="${2:-}"
# The remote with any embedded credentials stripped. Anything that gets COMMITTED
# must use this form -- a token in tracked content is published forever.
CLEAN_REMOTE="$(printf '%s' "$REMOTE" | sed -E 's#//[^/@]*@#//#')"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$WORK"
git init -q -b main .
git config user.email "systest@dcms.local"
git config user.name  "DCMS System Test"
git config core.autocrlf false

# ------------------------------------------------------------------ helpers --
commit() { git add -A; git commit -qm "$1"; }

# Start every fx/ branch from the same known-good base so a diff against main
# shows exactly, and only, the scenario under test.
from_main() { git checkout -q main; git checkout -q -B "$1"; }

node_app() {
  cat > package.json <<'JSON'
{
  "name": "dcms-fixture",
  "version": "1.0.0",
  "private": true,
  "scripts": { "start": "node server.js" }
}
JSON
  cat > server.js <<'JS'
const http = require('http');
const port = process.env.PORT || 3000;
const marker = process.env.DCMS_FIXTURE_MARKER || 'dcms-fixture-ok';
http.createServer((req, res) => {
  if (req.url === '/health') { res.writeHead(200); return res.end('ok'); }
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end(`<!doctype html><title>DCMS fixture</title><h1>${marker}</h1><p>branch marker</p>`);
}).listen(port, '0.0.0.0', () => console.log('listening on ' + port));
JS
}

# ------------------------------------------------------------- main (control) --
# The control: a minimal working Node app that must always deploy cleanly.
# Used by HOOK-*, AI-PUSH-*, and as the baseline every other branch diverges from.
node_app
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
cat > README.md <<'MD'
# DCMS fixture repository

Generated by `fixtures/build-branches.sh`. **Do not hand-edit branches** — change
the generator and re-run it, so the corpus stays reproducible.

Each `fx/*` branch isolates one awkward deployment scenario from SYSTEM-TEST.MD
sections 8.7 and 8.8. `main` is the control: a minimal Node app that must always
deploy cleanly. If `main` fails, the harness is broken, not the product.
MD
mkdir -p fixtures
cp "$0" fixtures/build-branches.sh 2>/dev/null || true
chmod +x fixtures/build-branches.sh 2>/dev/null || true
commit "main: minimal working Node app (the control fixture)"

# ------------------------------------------------------------------ develop --
# R-WX-03: default branch is not `main`. Same app, different branch name.
from_main develop
sed -i "s/dcms-fixture-ok/dcms-fixture-develop/" server.js
commit "develop: same app on a non-main default branch (R-WX-03)"

# ------------------------------------------------- fx/no-dockerfile-no-stack --
# INS-NEG-07 / R-WX-16: nothing deployable. Expect a clear 400 with guidance.
from_main fx/no-dockerfile-no-stack
git rm -q -f Dockerfile package.json server.js
cat > README.md <<'MD'
# Documentation only

There is no application here — no Dockerfile, no package.json, no recognisable
stack. Deploying this must produce a clear, actionable 400, never a 500 and
never a hang.
MD
mkdir -p docs && echo "Just some prose." > docs/notes.md
commit "fx/no-dockerfile-no-stack: docs only, nothing deployable (INS-NEG-07)"

# ------------------------------------------------------ fx/dockerfile-subdir --
# R-WX-05: Dockerfile lives in docker/, not at the repo root.
from_main fx/dockerfile-subdir
mkdir -p docker && git mv Dockerfile docker/Dockerfile
commit "fx/dockerfile-subdir: Dockerfile in docker/ (R-WX-05)"

# --------------------------------------------------- fx/dockerfile-lowercase --
# R-WX-06: lowercase `dockerfile`. Docker accepts it; detection must too.
from_main fx/dockerfile-lowercase
git mv Dockerfile dockerfile.tmp && git mv dockerfile.tmp dockerfile
commit "fx/dockerfile-lowercase: lowercase dockerfile (R-WX-06)"

# ---------------------------------------------------------------- fx/no-expose --
# R-WX-07: valid Dockerfile with no EXPOSE. Port must be detected at runtime.
from_main fx/no-expose
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
CMD ["npm", "start"]
DOCKER
commit "fx/no-expose: no EXPOSE directive (R-WX-07)"

# -------------------------------------------------------------- fx/volume-root --
# R-WX-08: VOLUME declared over the project root — a nested-mount trap.
from_main fx/volume-root
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
VOLUME /app
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/volume-root: VOLUME over the project root (R-WX-08)"

# --------------------------------------------------------------- fx/multistage --
from_main fx/multistage
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine AS build
WORKDIR /src
COPY package.json ./
COPY server.js ./
RUN mkdir -p /out && cp package.json server.js /out/

FROM node:22-alpine
WORKDIR /app
COPY --from=build /out/ ./
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/multistage: multi-stage build"

# -------------------------------------------------------------- fx/nonroot-user --
from_main fx/nonroot-user
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
RUN addgroup -S app && adduser -S app -G app && chown -R app:app /app
USER app
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/nonroot-user: USER app in the final stage"

# ------------------------------------------------------------ fx/entrypoint-cmd --
from_main fx/entrypoint-cmd
cat > docker-entrypoint.sh <<'SH'
#!/bin/sh
set -e
echo "entrypoint: starting with args: $*"
exec "$@"
SH
chmod +x docker-entrypoint.sh
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["npm", "start"]
DOCKER
commit "fx/entrypoint-cmd: ENTRYPOINT + CMD split"

# --------------------------------------------------------------- fx/healthcheck --
from_main fx/healthcheck
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
EXPOSE 3000
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/health || exit 1
CMD ["npm", "start"]
DOCKER
commit "fx/healthcheck: Dockerfile HEALTHCHECK"

# ---------------------------------------------------------------- fx/build-args --
from_main fx/build-args
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
ARG BUILD_MARKER
RUN test -n "$BUILD_MARKER" || (echo "BUILD_MARKER build-arg is required" >&2; exit 1)
WORKDIR /app
COPY package.json ./
COPY server.js ./
ENV DCMS_FIXTURE_MARKER=$BUILD_MARKER
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/build-args: build fails without an ARG"

# ---------------------------------------------------------------- fx/distroless --
# INS-NEG-15: shell-less final image.
from_main fx/distroless
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine AS build
WORKDIR /src
COPY package.json server.js ./

FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
COPY --from=build /src/server.js ./
COPY --from=build /src/package.json ./
EXPOSE 3000
CMD ["server.js"]
DOCKER
commit "fx/distroless: shell-less final image (INS-NEG-15)"

# ------------------------------------------------------------ fx/bind-localhost --
# INS-NEG-01: the classic. Binds 127.0.0.1, so it is unreachable from outside
# the container. DCMS must diagnose this specifically, not just time out.
from_main fx/bind-localhost
sed -i "s/}).listen(port, '0.0.0.0'/}).listen(port, '127.0.0.1'/" server.js
grep -q "127.0.0.1'" server.js || { echo "bind-localhost patch failed" >&2; exit 1; }
commit "fx/bind-localhost: app binds 127.0.0.1 (INS-NEG-01)"

# --------------------------------------------------------- fx/exit-immediately --
# INS-NEG-02: process exits at once; crash-loop guard must trip.
from_main fx/exit-immediately
cat > server.js <<'JS'
console.error('fixture: exiting immediately on purpose');
process.exit(1);
JS
commit "fx/exit-immediately: process exits on start (INS-NEG-02)"

# ----------------------------------------------------------------- fx/slow-start --
# INS-NEG-03: ready only after ~150s. Must not be killed prematurely.
from_main fx/slow-start
cat > server.js <<'JS'
const http = require('http');
const port = process.env.PORT || 3000;
const DELAY_MS = 150000;
console.log('fixture: sleeping ' + DELAY_MS + 'ms before listening');
setTimeout(() => {
  http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end('<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-slow-start</h1>');
  }).listen(port, '0.0.0.0', () => console.log('listening on ' + port));
}, DELAY_MS);
JS
commit "fx/slow-start: ready after ~150s (INS-NEG-03)"

# -------------------------------------------------------------- fx/port-mismatch --
# App listens on 4567 while EXPOSE says 3000.
from_main fx/port-mismatch
sed -i "s/process.env.PORT || 3000/process.env.PORT || 4567/" server.js
commit "fx/port-mismatch: listens on a port != EXPOSE"

# ------------------------------------------------------------- fx/needs-port-env --
# Only works if PORT is injected; no default.
from_main fx/needs-port-env
cat > server.js <<'JS'
const http = require('http');
const port = process.env.PORT;
if (!port) {
  console.error('fixture: PORT must be injected; refusing to guess');
  process.exit(1);
}
http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end('<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-needs-port-env</h1>');
}).listen(port, '0.0.0.0', () => console.log('listening on ' + port));
JS
commit "fx/needs-port-env: requires PORT injection"

# ------------------------------------------------------------- fx/native-modules --
# INS-NEG-04: native modules on alpine/musl. Known fragile class.
from_main fx/native-modules
cat > package.json <<'JSON'
{
  "name": "dcms-fixture-native",
  "version": "1.0.0",
  "private": true,
  "scripts": { "start": "node server.js" },
  "dependencies": {
    "sharp": "^0.33.0",
    "bcrypt": "^5.1.1",
    "canvas": "^2.11.2"
  }
}
JSON
cat > server.js <<'JS'
const http = require('http');
require('sharp'); require('bcrypt'); require('canvas');
const port = process.env.PORT || 3000;
http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end('<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-native-modules</h1>');
}).listen(port, '0.0.0.0', () => console.log('listening on ' + port));
JS
commit "fx/native-modules: sharp + bcrypt + canvas (INS-NEG-04)"

# -------------------------------------------------------------- fx/python-wheels --
# INS-NEG-05: compiled wheels on python:slim.
from_main fx/python-wheels
git rm -q -f package.json server.js Dockerfile
cat > requirements.txt <<'TXT'
Flask==3.0.3
psycopg2==2.9.9
lxml==5.2.2
Pillow==10.3.0
TXT
cat > app.py <<'PY'
import os
from flask import Flask
import psycopg2, lxml, PIL  # noqa: F401  -- imported to prove the wheels built

app = Flask(__name__)

@app.route("/")
def index():
    return "<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-python-wheels</h1>"

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 3000)))
PY
commit "fx/python-wheels: psycopg2 + lxml + Pillow (INS-NEG-05)"

# ------------------------------------------------------------- fx/php-extensions --
# INS-NEG-06: needs gd, intl, zip, imagick. Static analysis must detect them.
from_main fx/php-extensions
git rm -q -f package.json server.js Dockerfile
cat > index.php <<'PHP'
<?php
$required = ['gd', 'intl', 'zip', 'imagick'];
$missing = array_values(array_filter($required, fn($e) => !extension_loaded($e)));
if ($missing) {
    http_response_code(500);
    echo "<h1>missing extensions: " . implode(', ', $missing) . "</h1>";
    exit(1);
}
$img = imagecreatetruecolor(1, 1);           // gd
$fmt = new NumberFormatter('en_US', NumberFormatter::DECIMAL);  // intl
echo "<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-php-extensions</h1>";
PHP
cat > composer.json <<'JSON'
{
  "name": "dcms/fixture-php-extensions",
  "require": {
    "php": ">=8.1",
    "ext-gd": "*",
    "ext-intl": "*",
    "ext-zip": "*",
    "ext-imagick": "*"
  }
}
JSON
commit "fx/php-extensions: needs gd/intl/zip/imagick (INS-NEG-06)"

# ----------------------------------------------------------- fx/broken-dockerfile --
# INS-NEG-13: a RUN step that fails. Build log must surface the failing step.
from_main fx/broken-dockerfile
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
RUN echo "about to fail on purpose" && this-command-does-not-exist --nope
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/broken-dockerfile: failing RUN step (INS-NEG-13)"

# ---------------------------------------------------------- fx/postinstall-fails --
# R-WX-17: npm postinstall exits non-zero.
from_main fx/postinstall-fails
cat > package.json <<'JSON'
{
  "name": "dcms-fixture-postinstall",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "postinstall": "node -e \"console.error('postinstall failing on purpose'); process.exit(3)\"",
    "start": "node server.js"
  }
}
JSON
commit "fx/postinstall-fails: failing postinstall (R-WX-17)"

# ---------------------------------------------------------- fx/npm-run-dev-only --
# R-WX-10: no start, no build. Expect the documented "no entrypoint" error.
from_main fx/npm-run-dev-only
git rm -q -f Dockerfile
cat > package.json <<'JSON'
{
  "name": "dcms-fixture-dev-only",
  "version": "1.0.0",
  "private": true,
  "scripts": { "dev": "node server.js" }
}
JSON
commit "fx/npm-run-dev-only: only a dev script (R-WX-10)"

# ------------------------------------------------------------ fx/data-and-shared --
# INS-NEG-16 / R-WX-11: repo ships data/ and shared/, colliding with DCMS mounts.
# The repo's own files must never be overwritten.
from_main fx/data-and-shared
mkdir -p data shared
echo "repo-owned data file - must survive deployment" > data/repo-data.txt
echo "repo-owned shared file - must survive deployment" > shared/repo-shared.txt
commit "fx/data-and-shared: repo ships data/ and shared/ (INS-NEG-16)"

# ------------------------------------------------------------- fx/weird-filenames --
# INS-NEG-17 / R-WX-12: spaces, unicode, #, very deep paths, symlinks.
# Built on Linux so symlinks and unicode are real rather than emulated.
from_main fx/weird-filenames
mkdir -p "weird files"
echo "space in dir and name" > "weird files/a file with spaces.txt"
echo "hash in name"          > "weird files/has#hash.txt"
echo "unicode name"          > "weird files/ünïcødé-文件-📦.txt"
echo "leading dash"          > "weird files/--dashed.txt"
deep="deep"; for i in $(seq 1 12); do deep="$deep/level-$i-padding-padding-padding"; done
mkdir -p "$deep"; echo "deep file" > "$deep/leaf.txt"
ln -sf "../a file with spaces.txt" "weird files/link-to-spaces.txt" 2>/dev/null || true
ln -sf "/etc/passwd" "weird files/link-outside-workspace" 2>/dev/null || true
commit "fx/weird-filenames: spaces, unicode, #, deep paths, symlinks (INS-NEG-17)"

# ------------------------------------------------------------- fx/env-committed --
# R-WX-09: a committed .env plus .env.example. No secret may leak into the UI
# or logs.
from_main fx/env-committed
cat > .env <<'ENV'
APP_SECRET=committed-secret-value-must-not-leak
DATABASE_URL=postgres://user:committed-password@db:5432/app
API_KEY=sk-committed-fixture-key-0000
ENV
cat > .env.example <<'ENV'
APP_SECRET=
DATABASE_URL=
API_KEY=
ENV
commit "fx/env-committed: committed .env + .env.example (R-WX-09)"

# ----------------------------------------------------------------- fx/compose-only --
# INS-NEG-09 / R-WX-15: compose file, no Dockerfile. Expect clear guidance.
from_main fx/compose-only
git rm -q -f Dockerfile
cat > docker-compose.yml <<'YML'
services:
  web:
    build: .
    ports: ["3000:3000"]
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: fixture
YML
commit "fx/compose-only: docker-compose.yml, no Dockerfile (INS-NEG-09)"

# ------------------------------------------------------------------ fx/writes-cwd --
# R-WX-18: non-root app writing to its CWD. The README's known permission case.
from_main fx/writes-cwd
cat > server.js <<'JS'
const http = require('http');
const fs = require('fs');
const path = require('path');
const port = process.env.PORT || 3000;
http.createServer((req, res) => {
  const target = path.join(process.cwd(), 'runtime-generated.txt');
  try {
    fs.writeFileSync(target, 'written at ' + new Date().toISOString() + '\n');
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end('<!doctype html><title>DCMS fixture</title><h1>dcms-fixture-writes-cwd OK</h1>');
  } catch (err) {
    res.writeHead(500, { 'Content-Type': 'text/plain' });
    res.end('write to CWD failed: ' + err.message);
  }
}).listen(port, '0.0.0.0', () => console.log('listening on ' + port));
JS
cat > Dockerfile <<'DOCKER'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY server.js ./
RUN addgroup -S app && adduser -S app -G app
USER app
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
commit "fx/writes-cwd: non-root app writing to CWD (R-WX-18)"

# ------------------------------------------------------------ fx/force-push-target --
# INS-NEG-12 / R-WX-20: a dedicated branch whose history gets rewritten, so no
# other test's history is ever touched.
from_main fx/force-push-target
sed -i "s/dcms-fixture-ok/dcms-fixture-force-push-v1/" server.js
commit "fx/force-push-target: v1 history, to be rewritten by INS-NEG-12"

git checkout -q main

# ------------------------------------------------------------------------ push --
BRANCHES=$(git for-each-ref --format='%(refname:short)' refs/heads/)
echo "built branches:"; echo "$BRANCHES" | sed 's/^/  /'

if [ "$PUSH" = "--push" ]; then
  git remote add origin "$REMOTE" 2>/dev/null || git remote set-url origin "$REMOTE"
  # force-with-lease is wrong here: these branches are generated, and the whole
  # point is that the generator is authoritative over whatever is upstream.
  git push -q --force origin $(echo "$BRANCHES" | tr '\n' ' ')
  echo "pushed $(echo "$BRANCHES" | grep -c .) branches to origin"
fi

# ==============================================================================
# Not built here, and why:
#
#   fx/lfs        R-WX-02 needs a real Git LFS asset. git-lfs is deliberately NOT
#                 installed on the DCMS host, because whether DCMS's clone path
#                 fetches LFS content or leaves pointer files is exactly what
#                 R-WX-02 measures. Build this branch from a machine that has
#                 git-lfs and push it separately.
#
#   fx/big-binary R-WX-19 asks for a 200 MB binary in the tree. GitHub rejects
#                 any blob over 100 MB when LFS is not in use, so the fixture as
#                 specified cannot be pushed. Build it at ~95 MB, or host it on
#                 GitLab only, and record the deviation.
# ==============================================================================

# ------------------------------------------------------------------ fx/submodules --
# R-WX-01: a real git submodule, pointing at this same repo so the fixture stays
# self-contained and depends on no third party.
#
# This runs AFTER the push on purpose. A submodule needs its target to have at
# least one commit, and on a first run the remote is empty until the push above
# lands -- so building this branch earlier fails with
# "does not have a commit checked out".
if [ "$PUSH" = "--push" ]; then
  from_main fx/submodules
  if git -c protocol.file.allow=always submodule add -q -b main "$REMOTE" vendor/self 2>/dev/null; then
    # `submodule add` records whatever URL it was given -- including credentials.
    # Writing the tokenised URL into .gitmodules would publish the PAT in a repo
    # that is public; GitHub push protection rejects it, and rightly so. Rewrite
    # the recorded URL to the credential-free form before committing. The push
    # itself still authenticates through `origin`.
    git config -f .gitmodules submodule.vendor/self.url "$CLEAN_REMOTE"
    git add .gitmodules
    commit "fx/submodules: one git submodule (R-WX-01)"
    git push -q --force origin fx/submodules
    echo "pushed fx/submodules"
  else
    echo "WARNING: fx/submodules could not be built (submodule add failed); branch skipped" >&2
  fi
  git checkout -q main
fi

